config/routes.rb
Rails.application.routes.draw do
  # default / home
  root 'home#index'

  # ckeditor engine
  mount Ckeditor::Engine => '/ckeditor'
  
  # normal routes
  get 'cv/index'
  get 'about' => 'about#index'
  get 'cv' => 'cv#index'
  get 'home/index'
  get 'search' => 'search#index'
  get 'tags/index'


  # tag autocomplete routes
  get '/admin/autocomplete_tags',
  to: 'admin/words#autocomplete_tags',
  as: 'autocomplete_tags'

  
  # active admin routes
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  # resources
  resources :articles, :path => 'words'
  resources :tags, only: [:index, :show], param: :slug
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	# Relationships

	# Validations
	validates :title, presence: true, length: { minimum: 5 }

	# Callbacks
  	before_save :generate_slug
  	after_destroy :cleanup_after_deletion

	# Scopes
	default_scope { order( created_at: :desc ) }

	# Third party
	extend FriendlyId
	friendly_id :title, use: :slugged
	include AlgoliaSearch

	algoliasearch do
	    attributes :title, :content
	    attributesToIndex %w(title content)
	end
	
	acts_as_taggable_on :tags
	acts_as_paranoid
	is_impressionable
	
	# Methods

	private
		def cleanup_after_deletion
			puts "Deleted article"
		end

	  	def generate_slug
		    if self.slug.present? && self.slug == title.parameterize
		      self.slug
		    else
		      self.slug = title.parameterize
			end
		end

	  	# Accessor method to determine if a new friendly id should be generated
	  	def should_generate_new_friendly_id?
	    	new_record?
	  	end

		# the field candidates for the slug
		def slug_candidates
	    [
	      :title
	    ]
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  impressionist :actions=> [:index]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		by_month = Article.includes(:impressions).where('published = true').group_by { |m| m.created_at.beginning_of_month }
		per_page = 4
		@articles_by_month = Kaminari.paginate_array(by_month.sort.reverse).page(params[:page]).per(per_page)
		@page = params[:page] ? params[:page] : 1
		@total_pages = (by_month.length.to_f / per_page.to_f).ceil
	end

	def show
		@article = Article.includes(:impressions).friendly.find(params[:id])
		impressionist(@article)
		@impression_count = @article.impressionist_count(:filter=>:all)
	end

	private
		def article_params
			params.require(:article).permit(:title, :content, :slug, :tag_list)
		end
end

app/controllers/cv_controller.rb
class CvController < ApplicationController

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@recent_articles = Article.where('published = true').order('created_at DESC').limit(5)
	end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  impressionist :actions=>[:index]
  def index
  	@q = params['q']
    return if @q.blank?
    @hits = Article.algolia_search(@q)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    respond_to do |format|
      @tags = ActsAsTaggableOn::Tag.where('taggings_count > 0').order('taggings_count desc')
      format.html
      format.json { render json: @tags }
    end
  end

  def show
    # The ! will raise a RecordNotFound exception resulting in a 404 page if no record found for the given tag.
    @tag =  ActsAsTaggableOn::Tag.friendly.find_by!(slug: params[:slug])
    @query = params[:slug]
    unless @tag.nil?
        @articles = Article.tagged_with(@tag.name)
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
	  content_for :title, "ajb: #{page_title.to_s}"
	end
	def meta_tag(tag, text)
	    content_for :"meta_#{tag}", text
	end

	def yield_meta_tag(tag, default_text='')
	    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  # def article_path(article, options={})
  #   article_url(article, options.merge(:only_path => true))
  # end

  # def article_url(article, options={})
  #   url_for(options.merge(:controller => 'articles', :action => 'show',
  #                         :id => article.id, :slug => article.slug))
  # end
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/about/index.html.erb
<% title 'About' %>

<section class="about-me narrow">
	<h1>About me</h1>
	<p class="lead">
		Hi there, my name is <strong>Adam Bull</strong> and I am a recovering .NET developer forging a new path in the wonderful world of Ruby on Rails. I am super stoked for what lies ahead.
	</p>
	<p>I originally studied English Literature for my undergraduate degree way back in 2008 – lots of lofty discussions about postmodern poetry and national identity in the poetry of Philip Larkin – that kinda stuff. I had always thought that I was an “arty” person rather than a “techy” one so I spent most of my early life blinded by this assumption. And then I saw the light..</p>
	<p>After finishing university, I decided that I’d like to get into programming having always been a dab hand at computer-y sort of stuff. I stumbled across the Computer Science MSc conversion course at the University of Hertfordshire in early 2012 and haven't looked back. I have been programming seriously coming up to 4 years now and I have learnt all sorts of weird &amp; wonderful stuff.</p>
	<p>I always like to experiment with new things; my ethos is to leave no stone unturned. I very much hold the polyglot developer mindset, and I think it’s important to have wide-ranging knowledge in a variety of programming languages and technologies.</p>

	<p>
		If you find an error on my blog, then please email me at <a href="mailto:hello@adamjamesbull.co.uk">hello@adamjamesbull.co.uk</a> and I will correct it.<br/><br/>You can also find me at various other places online, check out the links below.
	</p>

	<div class="horizontal-links">
		<p>
			<a href="https://github.com/adaam2">GitHub</a>
		</p>
		<p>
			<a href="https://bitbucket.com/adaam2">BitBucket</a>
		</p>
	</div>	
</section>

app/views/acts_as_taggable_on/tags/_tag.html.erb
<li class="tag">
	<%= link_to "#{tag.name}", tag_path(tag.slug) %> 
	<% if tag.taggings_count == 1 %>
		<span class="faded">(<%= tag.taggings_count %><span class="descriptor">&nbsp;article</span>)</span>
	<% else %>
		<span class="faded">(<%= tag.taggings_count %><span class="descriptor">&nbsp;articles</span>)</span>
	<% end %>	
</li>

app/views/articles/_article.html.erb
<li><%= link_to article.title, article_path(article) %></li>

app/views/articles/index.html.erb
<% title 'Articles' %>

<section class="articles cf">
<h1>Articles</h1>

<% if @articles_by_month.blank? %>
	<p>No posts at the moment! :(</p>
<% else %>

	<div class="months">

		<% @articles_by_month.each do |month, articles| %>
			<div class="month-group" data-month="<%= month.strftime('%B-%Y') %>">
				<h2 class="month">
					<%= month.strftime('%B %Y') %>
				</h2>

				<ul class="bulleted post-list">
					<% articles.each do |article| %>
					<li>
						<%= link_to article.title, article_path(article) %>
					</li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="pagination-controls">
			<%= paginate @articles_by_month %>
		</div>
	</div>
<% end %>
</section>

app/views/articles/show.html.erb
<% title "#{@article.title}" %>

<% if @article.imported_from_wordpress %>
  <p class="faded">
    This article was originally posted on my Wordpress site between 2011 - 2014. The article content may be out of date, and code formatting may be malformed. If you spot an error, please email me at <a href="mailto:hello@adamjamesbull.co.uk">hello@adamjamesbull.co.uk</a>.
  </p>
<% end %>
<section id="article" class="narrow">
  <article class="article">
    <h1><%= @article.title %></h1>

    <div class="article-meta">     
      <p class="faded">
        <span class="meta-item">
          <i class="fa fa-eye" title="Page views" aria-hidden="true"></i> <%= @article.impressions.size %> views
        </span>
        <span class="meta-item">
          <i class="fa fa-calendar" title="Post date" aria-hidden="true"></i> <%= @article.created_at.strftime("#{@article.created_at.day.ordinalize} %B %Y") %>
        </span>
      </p>
    </div>
    <div class="article-body">
      <%= raw(@article.content) %>
    </div>
    <% if @article.tags.count > 1 %>
        <div class="article-tags">

          <h3>Tags:</h3>
          <ul class="tag-cloud">
            <%= render @article.tags %>
          </ul>
        </div>
    <% end %>

    <div class="article-comments">
      <div id="disqus_thread"></div>
    </div>

  </article>

</section>
<script type="text/javascript">
var disqus_config = function () {
    this.page.url = '<%= request.original_url %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @article.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};

(function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = '//adamjameasbullcouk.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/cv/index.html.erb
<% title 'Curriculum vitae' %>
<section class="curriculum-vitae narrow">
	<h1>
		Curriculum vitae
	</h1>
	<p>
		My CV is also available in print format <a href="https://www.adamjamesbull.co.uk/cv.pdf" target="_blank">here</a>.
	</p>
	<br/>
	<h2>Preamble</h2>
	<p>
		Having previously worked as an ASP.NET developer for around 4 years and having completed a Masters (MSc) in Computer Science at the University of Hertfordshire, I have a strong grasp of object orientation and enterprise software development patterns and development practices. Nowadays I am working as a Ruby on Rails developer, and it feels a little like starting out again (yet this time around I have a few more tools in my shed so to speak). 
	</p>
	<section class="education">
		<h2>Education</h2>
		<div class="item">
			<p>
				<strong>
					MSc in Computer Science (with Distinction)
				</strong>
				<i>University of Hertfordshire (2013-2014)</i>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					BA in English Literature (2nd class honours)
				</strong>
				<i>University of Reading (2008-2011)</i>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					3 A Levels, 11 GCSEs (all A* - C)
				</strong>

				<i>St. Columba's College, St Albans, Hertfordshire (2001-2008)</i>
			</p>
		</div>
	</section>
	<section class="employment-history">
		<h2>Employment history</h2>
		<div class="item">
			<p>
				<strong>
					Ruby on Rails Developer at Farmdrop
				</strong>
				<i>
					London, United Kingdom
				</i>
				<span class="faded">
					(March 2017 - Present)
				</span>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					Ruby on Rails Developer at Route1
				</strong>
				<i>
					London, United Kingdom
				</i>
				<span class="faded">
					(January 2017 - March 2017)
				</span>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					C# Developer at MB Interactive
				</strong>
				<i>
					St Albans, United Kingdom
				</i>
				<span class="faded">
					(July 2013 - December 2016)
				</span>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					PHP / Wordpress Developer at Mang Creative
				</strong>
				<i>
					Hemel Hempstead, United Kingdom
				</i>
				<span class="faded">
					(May 2013 - July 2013)
				</span>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					Digital Assistant at Audit Bureau of Circulations
				</strong>
				<i>
					Berkhampstead, United Kingdom
				</i>
				<span class="faded">
					(September 2012 - December 2012)
				</span>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					Data Analyst at Air Business
				</strong>
				<i>
					St Albans, United Kingdom
				</i>
				<span class="faded">
					(April 2012 - September 2012)
				</span>
			</p>
		</div>
		<div class="item">
			<p>
				<strong>
					I.T Assistant at Justin Craig Education
				</strong>
				<i>
					London Colney, United Kingdom
				</i>
				<span class="faded">
					(January 2012 - April 2012)
				</span>
			</p>
		</div>
	</section>

	<section class="contact">
		<h2>Contact me</h2>
		<p>
			If you would like to contact me regarding an opportunity, please email at <a href="mailto:hello@adamjamesbull.co.uk">hello@adamjamesbull.co.uk</a>.
		</p>
	</section>
</section>

app/views/home/index.html.erb
<% title 'Home' %>

<h2>
	About me
</h2>

<p>
	TLDR; I used to be a .NET developer, now I am a Rails developer.  <br/><a href="/about">More about me</a>.	
</p>

<% if @recent_articles %>
	<h2>
		Recent posts
	</h2>
	<ul class="bulleted post-list">
		<% @recent_articles.each do |article| %>
		<li>
			<%= link_to article.title, article_path(article) %>
		</li>
		<% end %>
	</ul>
<% end %>

app/views/search/index.html.erb
<% title "Search results for #{@q}" %>
<% meta_tag :description, "Search results for #{@q}" %>

<section class="search-results narrow">
	<h1><span class="tag"><%= "#{@q}" %></span></h1>

	<% if @hits.size > 0 %>
	  <div class="hits">
	  	<% @hits.each do |hit| %>
		    <div class="hit">
		      <div class="hit-link">
		      	<%= link_to hit['title'], article_path(hit) %>
		      </div>
		      <div class="hit-date">
		      	 <i class="fa fa-clock-o" aria-hidden="true"></i> <%= raw(hit['created_at'].strftime('%b %d, %Y')) %>
		      </div>
		    </div>
		  <% end %>
	  </div>
	 <% else %>
	 	<p>Oh no! You haven't struck gold this time. Try another search.</p>
	<% end %>
</section>

app/views/tags/index.html.erb
<% title 'Tags' %>

<section class="tags narrow">
  <h1>Topics</h1>

  <ul class="bulleted">
    <%= render @tags %>
  </ul>
</section>

app/views/tags/show.html.erb
<section class="tag-page narrow">

	<% if not @tag.nil? %>
		<h1><span class="tag"><%= "#{@tag.name}" %></span></h1>
		<% title "Tag - #{@tag.name}" %>
		<p>
		<% if @tag.taggings_count == 1 %>
			<strong><%= @tag.taggings_count %> article</strong> found:
		<% else %>
			<strong><%= @tag.taggings_count %> articles</strong> found:
		<% end %>	
		</p>
	
		<ul class="bulleted">
			<%= render @articles %>
		</ul>
	<% else %>
		<h1>
			<span class="tag"><%= @query %></span>
		</h1>
		
		<p>
			Sorry, but there were no results.
		</p>
	<% end %>
</section>